spring:
  application:
    name: barber-shop-api
  datasource:
    url: jdbc:postgresql://localhost:5432/baberSistem_db
    username: user
    password: root

  jpa:
    hibernate:
      ddl-auto: validate