FROM postgres:17.2

# Definir variáveis de ambiente padrão
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_ROOT_PASSWORD=root
ENV POSTGRES_DB=baberSistem_db

# Expor a porta padrão do PostgreSQL
EXPOSE 5432
